### ISSUE TITLE
Migration from legacy FCM to HTTP v1

### ISSUE THREAD

**Issue by ogenthe** [ToothlessGear/node-gcm#391] opened 2024-05-29 09:14 UTC
It looks as if legacy FCM APIs have been deprecated and will be removed on June 21 2024. 
[https://firebase.google.com/docs/cloud-messaging/migrate-v1](https://firebase.google.com/docs/cloud-messaging/migrate-v1)

The endpoints and authentication mechanisms seem to need to be updated. 
Does this mean that this package will stop working on June 21 2024?

**Comment by eladnava** [comment] 2024-05-29 13:09
Correct.

We do urge you to migrate to another library before the June 20th deadline, such as:
1. [firebase-admin](https://www.npmjs.com/package/firebase-admin) (official library)
2. [fcm-v1-http2](https://www.npmjs.com/package/fcm-v1-http2) (if throughput is important to your sending requirements)

Closing as this is a duplicate of issue #370.

**Closed by eladnava** 2024-05-29 13:09 UTC
