### ISSUE TITLE
send call sometimes hangs server 

### ISSUE THREAD

**Issue by 2fours** [ToothlessGear/node-gcm#36] opened 2013-12-02 18:07 UTC
With 0.9.7 I'm occasionally still seeing server hangs on send. It happens very rarely (once in 2-3 weeks). Could it be that in sender.js where the new timeout code (https://github.com/ToothlessGear/node-gcm/blob/master/lib/sender.js#L95) has been added that callback("timeout", null) needs to be called? I'm not sure if aborting the request will cause the error or end events to fire so the callback never gets called, is this possible?

**Comment by hypesystem** [comment] 2015-02-27 17:42
Hello guys! It's now been quite a while since you last checked this bug. Can you see if it is still present? If so, what are the steps to reproduce?

Sorry to poke you affter so long (I mean, the last comment on here was from 3 Jan 2014), but I'd like to know if this issue persists.

**Comment by hypesystem** [comment] 2015-07-15 17:36
No new reports of this problem, no idea if it is still one. Gonna close this.

**Closed by hypesystem** 2015-07-15 17:36 UTC
Labels: bug
